name: autotests

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  proxy-checker-test:
    runs-on: ubuntu-latest
    container: golang:1.26.1

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install dependencies
        run: apt-get install gcc pkg-config libgl1-mesa-dev xorg-dev libasound2-dev libfreetype6-dev libfontconfig1-dev

      - name: Build server binary
        run: |
          make clean lint test build
