name: autotests

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  proxy-checker-test:
    runs-on: ubuntu-latest
    container: golang:1.26.1

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Build server binary
        run: |
          make clean lint test build
